# Generated by Django 5.0.1 on 2024-04-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_user_rename_userdata_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
