# Generated by Django 5.0.1 on 2024-04-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
